
[upload]
url = "http://localhost:3000/api/readings"
key = "jiogioajiosa"


[[monitoring]]
category = "computer"
name = "CPU Temperature"
unit = "°C"
sensor_type = "Temperature"
query_name = "Core"

[[monitoring]]
category = "computer"
name = "CPU Usage"
unit = "%"
sensor_type = "Load"
query_name = "CPU Total"

[[monitoring]]
category = "computer"
name = "Memory Usage"
unit = "%"
sensor_type = "Load"
query_name = "Memory"